#!/usr/bin/env bash

set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_HONEYMARKER_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "~~~ :hammer: Enabling debug mode"
  set -x
fi

if [[ ${BUILDKITE_COMMAND_EXIT_STATUS:-0} != "0" ]]
then
  echo "--- Skipping honeymarker because the command failed"
  exit 0
fi


message=${BUILDKITE_PLUGIN_HONEYMARKER_MESSAGE}
writekey=${BUILDKITE_PLUGIN_HONEYMARKER_WRITEKEY}
dataset=${BUILDKITE_PLUGIN_HONEYMARKER_DATASET}
url=${BUILDKITE_PLUGIN_HONEYMARKER_URL:-""}
type=${BUILDKITE_PLUGIN_HONEYMARKER_TYPE:-"deploy"}
update=${BUILDKITE_PLUGIN_HONEYMARKER_UPDATE:-false}
updatekey=${BUILDKITE_PLUGIN_HONEYMARKER_UPDATEKEY:-""}
now=$(date '+%s')


if [[ $update == "true" ]]; then
  echo "--- :bee: Updating the marker to ${dataset}"
  marker_id=$(buildkite-agent meta-data get "honeymarker_${BUILDKITE_BUILD_ID}_${updatekey}")

  result=$(curl -X PUT -H "X-Honeycomb-Team: ${writekey}" \
    -d "{\"message\": \"${message}\", \"type\":\"${type}\", \"url\": \"${url}\" , \"end_time\": ${now}}" \
    https://api.honeycomb.io/1/markers/${dataset}/${marker_id})
fi


