#!/usr/bin/env bash

set -exuo pipefail

if [[ ${BUILDKITE_COMMAND_EXIT_STATUS:-0} != "0" ]]
then
  echo "--- Skipping honeymarker because the command failed"
  exit 0
fi


message=${BUILDKITE_PLUGIN_HONEYMARKER_MESSAGE}
writekey=${BUILDKITE_PLUGIN_HONEYMARKER_WRITEKEY}
dataset=${BUILDKITE_PLUGIN_HONEYMARKER_DATASET}
url=${BUILDKITE_PLUGIN_HONEYMARKER_URL:-""}
type=${BUILDKITE_PLUGIN_HONEYMARKER_TYPE:-"deploy"}
update=${BUILDKITE_PLUGIN_HONEYMARKER_UPDATE:-false}
updatekey=${BUILDKITE_PLUGIN_HONEYMARKER_UPDATEKEY:-""}
now=$(date '+%s')


if [[ $update == "false" ]]; then

  echo "--- :bee: Adding a marker to ${dataset}"

  result=$(curl -X POST -H "X-Honeycomb-Team: ${writekey}" \
    -d "{\"message\": \"${message}\", \"type\":\"${type}\", \"url\": \"${url}\" , \"start_time\": ${now}}" \
    https://api.honeycomb.io/1/markers/${dataset})

  id=$(echo $result | jq -r ".id")

  echo "honeycomb id is $id"

  buildkite-agent meta-data set "honeymarker_${BUILDKITE_BUILD_ID}_${updatekey}" "${id}"
fi


